### ISSUE TITLE
[Incompatibility] Port conflict

### ISSUE THREAD

**Issue by JohnMetroid** [ZehsTeam/Lethal-Company-StreamOverlays#1]
Hey there,

Just a heads up, port 8080 probably conflicts with a bunch of other things.  At first, the stream overlays didn't work for me because of some websocket functionality VLC uses (I got a VLC error page when trying to use your Lethal overlays in either OBS or a browser).  I dug up your StreamOverlays file in the User/appdata folder and changed the port and it worked fine after I chose an unused port.  Perhaps moving this functionality forward to a mod manager config could be helpful for others?

Cheers

**Comment by ZehsTeam** [comment]
@ajsglist I'm not sure what port to use other than 8080 at the moment. The config file is stored in Lethal Company's app data folder because the settings vary per user and should not carry over with your mod codes and modpacks. You can easily edit the config settings in-game using the [LethalConfig](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/) mod.

The [LethalConfig](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/) mod is a soft dependency but I should add it as a Thunderstore dependency so people use it for editing the config settings easily. I've also added some [LethalConfig](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/) button to start and stop the server. When you edit the StreamOverlays config settings in the [LethalConfig](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/) mod, they apply immediately and don't require you to restart your game. If you change the port you will need to stop and start the server using the buttons I have added to the StreamOverlays [LethalConfig](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/) config settings page.

**Comment by JohnMetroid** [comment]
Ah, I didn't realize LethalConfig was hooked into it.  That makes sense.

Ultimately it was something I already troubleshooted (troubleshot?) on my end, but I just figured I'd pass it along since inevitably someone else will run into a port 8080 conflict.
